(printout t "Loading heroes..." crlf)
(load classes.clp)
(load heroes.clp)
(printout t "Done loading heroes." crlf)
(printout t "Setting up user information..." crlf)
(defglobal ?*User* = (make-instance User of PLAYER))
(printout t "Done setting up user information." crlf)
(printout t "Loading rules..." crlf)
(load rules.clp)
(printout t "Done loading rules" crlf)
(reset)
(printout t "System ready." crlf crlf)
(run)
